# Lints multiple NodeJS app(s) by calling their "lint" script
# https://github.com/orgs/community/discussions/11692#discussioncomment-3541856

name: Lint Node Apps

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node version i.e., 16.x, 16.14.2, etc."
        required: true
        type: string
        default: "16.14.2"
      paths:
        description: "List of directory paths to execute lint"
        required: false
        type: string
        default: "['./']"

jobs:
  lint-node-app:
    if: ${{ inputs.paths }}
    name: Lint Node App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJson(inputs.paths) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install Dependencies and lint
        run: |
          if [ -d "${{ matrix.path }}" ]; then
            echo "Entering... ${{ matrix.path }}"
            cd ${{ matrix.path }}
          else
            echo "Directory ${{ matrix.path }} does not exist."
            exit 1
          fi
          npm install
          npm run lint
